question_data = [
            {
                "type": "multiple",
                "difficulty": "medium",
                "category": "General Knowledge",
                "question": "What is a Burgee?",
                "correct_answer": "A flag",
                "incorrect_answers": ["A rope", "A window", "A type of food"],
            },
            {
                "type": "multiple",
                "difficulty": "medium",
                "category": "Entertainment: Film",
                "question": "Who voiced the character Draco in the 1996 movie &#039;DragonHeart&#039;?",
                "correct_answer": "Sean Connery",
                "incorrect_answers": [
                    "Dennis Quaid",
                    "Pete Postlethwaite",
                    "Brian Thompson",
                ],
            },
            {
                "type": "multiple",
                "difficulty": "easy",
                "category": "General Knowledge",
                "question": "In which fast food chain can you order a Jamocha Shake?",
                "correct_answer": "Arby&#039;s",
                "incorrect_answers": ["McDonald&#039;s", "Burger King", "Wendy&#039;s"],
            },
            {
                "type": "multiple",
                "difficulty": "easy",
                "category": "Geography",
                "question": "Which country does Austria not border?",
                "correct_answer": "France",
                "incorrect_answers": ["Slovenia", "Switzerland", "Slovakia"],
            },
            {
                "type": "multiple",
                "difficulty": "medium",
                "category": "Entertainment: Television",
                "question": "What episode of &quot;Mr. Bean&quot; saw him trying to prevent people from seeing him naked?",
                "correct_answer": "Mr. Bean in Room 426",
                "incorrect_answers": [
                    "Mr. Bean Goes to Town",
                    "The Trouble with Mr. Bean",
                    "Back to School Mr. Bean",
                ],
            },
            {
                "type": "boolean",
                "difficulty": "medium",
                "category": "General Knowledge",
                "question": "Only a small percentage of the world&#039;s population is lactose intolerant.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "type": "boolean",
                "difficulty": "easy",
                "category": "Entertainment: Video Games",
                "question": "Faust is a playable character in &quot;Guilty Gear Xrd Revelator&quot;.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "type": "multiple",
                "difficulty": "easy",
                "category": "General Knowledge",
                "question": "Antibiotics are generally taken to combat what?",
                "correct_answer": "Bacterial infections",
                "incorrect_answers": ["Viruses", "Migraines", "Muscular pains"],
            },
            {
                "type": "multiple",
                "difficulty": "hard",
                "category": "Sports",
                "question": "What is &ldquo;The Sport of Kings&rdquo;?",
                "correct_answer": "Horse Racing",
                "incorrect_answers": ["Chess", "Jousting", "Fencing"],
            },
            {
                "type": "boolean",
                "difficulty": "medium",
                "category": "History",
                "question": "United States President Ronald Reagan was the first president to appoint a woman to the Supreme Court. ",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "type": "multiple",
                "difficulty": "medium",
                "category": "Geography",
                "question": "The following Spanish provinces are located in the northern area of Spain except:",
                "correct_answer": "Murcia",
                "incorrect_answers": ["Asturias", "Navarre", "Le&oacute;n"],
            },
            {
                "type": "multiple",
                "difficulty": "easy",
                "category": "Entertainment: Music",
                "question": "Which 80s band is fronted by singer\/guitarist Robert Smith?",
                "correct_answer": "The Cure",
                "incorrect_answers": [
                    "The Smiths",
                    "Echo &amp; the Bunnymen",
                    "New Order",
                ],
            },
            {
                "type": "multiple",
                "difficulty": "easy",
                "category": "Entertainment: Music",
                "question": "Which of these songs by Skrillex features Fatman Scoop as a side artist?",
                "correct_answer": "Recess",
                "incorrect_answers": [
                    "All is Fair in Love and Brostep",
                    "Rock N Roll (Will Take You to the Mountain)",
                    "Scary Monsters and Nice Sprites",
                ],
            },
            {
                "type": "multiple",
                "difficulty": "medium",
                "category": "Entertainment: Video Games",
                "question": "In Yakuza 4 who is the first character you play as?",
                "correct_answer": "Shun Akiyama",
                "incorrect_answers": ["Taiga Saejima", "Kazuma Kiryu", "Goro Majima"],
            },
            {
                "type": "multiple",
                "difficulty": "easy",
                "category": "General Knowledge",
                "question": "What is Tasmania?",
                "correct_answer": "An Australian State",
                "incorrect_answers": [
                    "A flavor of Ben and Jerry&#039;s ice-cream",
                    "A Psychological Disorder",
                    "The Name of a Warner Brothers Cartoon Character",
                ],
            },
            {
                "type": "multiple",
                "difficulty": "medium",
                "category": "General Knowledge",
                "question": "What is the defining characteristic of someone who is described as hirsute?",
                "correct_answer": "Hairy",
                "incorrect_answers": ["Rude", "Funny", "Tall"],
            },
            {
                "type": "boolean",
                "difficulty": "medium",
                "category": "Entertainment: Japanese Anime &amp; Manga",
                "question": "The anime Attack on Titan was directed by Tetsur\u014d Araki, the same person who directed the anime Highschool of the Dead.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "type": "multiple",
                "difficulty": "medium",
                "category": "General Knowledge",
                "question": "What is the name of the very first video uploaded to YouTube?",
                "correct_answer": "Me at the zoo",
                "incorrect_answers": [
                    "tribute",
                    "carrie rides a truck",
                    "Her new puppy from great grandpa vern.",
                ],
            },
            {
                "type": "multiple",
                "difficulty": "hard",
                "category": "Entertainment: Video Games",
                "question": "In the game Enter the Gungeon, which one of these is not a playable character?",
                "correct_answer": "The Wizard",
                "incorrect_answers": ["The Bullet", "The Robot", "The Cultist"],
            },
            {
                "type": "multiple",
                "difficulty": "hard",
                "category": "Entertainment: Film",
                "question": "In what year does Jurassic World open in the &quot;Jurassic Park&quot; universe?",
                "correct_answer": "2005",
                "incorrect_answers": ["2007", "2015", "2020"],
            },
]
